### PR TITLE
Improved Python 3 compatibility.

### PR DESCRIPTION
**Pull request by frenzymadness**
Hello.

I am providing changes which improve Python 3 compatibility. All tests pass in both versions of Python.

**Python 2**
```
$ python --version
Python 2.7.12
$ python setup.py test
running test
running egg_info
writing okaara.egg-info/PKG-INFO
writing top-level names to okaara.egg-info/top_level.txt
writing dependency_links to okaara.egg-info/dependency_links.txt
reading manifest file 'okaara.egg-info/SOURCES.txt'
writing manifest file 'okaara.egg-info/SOURCES.txt'
running build_ext
test_found_section_not_command (test_cli.FindClosestMatchTests) ... ok
test_good_section_bad_section_good_section (test_cli.FindClosestMatchTests) ... ok
test_no_match_at_all (test_cli.FindClosestMatchTests) ... ok
test_successful_find_command (test_cli.FindClosestMatchTests) ... ok
test_valid_extensions (test_extensions.DirectoryExtensionsLoader) ... ok
test_load (test_extensions.ExtensionsManagerTests) ... ok
test_load_with_error (test_extensions.ExtensionsManagerTests) ... ok
test_invalid (test_parsers.ParseBooleanTests) ... ok
test_optional (test_parsers.ParseBooleanTests) ... ok
test_optional_empty_string (test_parsers.ParseBooleanTests) ... ok
test_optional_invalid (test_parsers.ParseBooleanTests) ... ok
test_optional_valid (test_parsers.ParseBooleanTests) ... ok
test_required (test_parsers.ParseBooleanTests) ... ok
test_valid_false (test_parsers.ParseBooleanTests) ... ok
test_valid_true (test_parsers.ParseBooleanTests) ... ok
test_basic_values (test_parsers.ParseCSVTests) ... ok
test_optional (test_parsers.ParseCSVTests) ... ok
test_optional_empty_string (test_parsers.ParseCSVTests) ... ok
test_optional_value (test_parsers.ParseCSVTests) ... ok
test_required (test_parsers.ParseCSVTests) ... ok
test_single_value (test_parsers.ParseCSVTests) ... ok
test_invalid (test_parsers.ParseIntTests) ... ok
test_valid (test_parsers.ParseIntTests) ... ok
test_negative (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_empty_string (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_invalid (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_valid (test_parsers.ParseNonNegativeIntTests) ... ok
test_string (test_parsers.ParseNonNegativeIntTests) ... ok
test_valid (test_parsers.ParseNonNegativeIntTests) ... ok
test_zero (test_parsers.ParseNonNegativeIntTests) ... ok
test_negative (test_parsers.ParsePostiveIntTests) ... ok
test_optional (test_parsers.ParsePostiveIntTests) ... ok
test_optional_empty_string (test_parsers.ParsePostiveIntTests) ... ok
test_optional_invalid (test_parsers.ParsePostiveIntTests) ... ok
test_optional_valid (test_parsers.ParsePostiveIntTests) ... ok
test_string (test_parsers.ParsePostiveIntTests) ... ok
test_valid (test_parsers.ParsePostiveIntTests) ... ok
test_zero (test_parsers.ParsePostiveIntTests) ... ok
test_color (test_prompt.GeneralTests)
Tests the color call correctly wraps the text with the correct markers. ... ok
test_read_interrupt (test_prompt.GeneralTests)
Tests that having read catch interrupt correctly returns the abort code. ... ok
test_write_color (test_prompt.GeneralTests)
Tests the color functionality built into write works. ... ok
test_write_with_wrap (test_prompt.GeneralTests)
Tests using an auto-wrap value correctly wraps text. ... ok
test_prompt_allow_empty (test_prompt.PromptTest)
Tests that a prompt will accept empty and not error. ... ok
test_prompt_menu (test_prompt.PromptTest)
Basic tests for prompting a menu of items and selecting a valid one. ... ok
test_prompt_no_empty (test_prompt.PromptTest)
Tests that a prompt that does not allow empty values re-prompts the user ... ok
test_prompt_non_interruptable (test_prompt.PromptTest)
Tests that a non-interruptable prompt properly raises an exception if interrupted. ... ok
test_prompt_password (test_prompt.PromptTest)
Make sure this correctly passes through to getpass one way or another ... ok
test_get_password (test_prompt.TestGetPassword) ... ok
test_py24_behavior (test_prompt.TestGetPassword) ... ok
test_py26_behavior (test_prompt.TestGetPassword) ... ok
test_wrap_long_wrap (test_prompt.WrapTests)
Tests that chop correctly handles data shorter than the chop length. ... ok
test_wrap_short_wrap (test_prompt.WrapTests)
Tests that chop correctly handled data longer than the chop length. ... ok
test_wrap_smart_split (test_prompt.WrapTests)
Tests smart wrapping to not break words. ... ok
test_wrap_with_none (test_prompt.WrapTests)
Tests that chop with a None wrap width doesn't crash. ... ok
test_equal_table_and_cols_no_separator (test_table.TableTests) ... ok
test_equal_table_and_cols_with_separator (test_table.TableTests) ... ok
test_larger_col_widths (test_table.TableTests) ... ok
test_larger_table_width (test_table.TableTests) ... ok
test_table_width_no_col_widths (test_table.TableTests) ... ok
test_invalid (test_validators.PartialValidateRegexTests) ... ok
test_valid (test_validators.PartialValidateRegexTests) ... ok
test_invalid (test_validators.ValidateBooleanTests) ... ok
test_valid (test_validators.ValidateBooleanTests) ... ok
test_invalid (test_validators.ValidateIntTests) ... ok
test_valid (test_validators.ValidateIntTests) ... ok

----------------------------------------------------------------------
Ran 66 tests in 0.047s

OK
```

**Python 3**
```
$ python --version
Python 3.5.1
$ python setup.py test
running test
running egg_info
writing top-level names to okaara.egg-info/top_level.txt
writing okaara.egg-info/PKG-INFO
writing dependency_links to okaara.egg-info/dependency_links.txt
reading manifest file 'okaara.egg-info/SOURCES.txt'
writing manifest file 'okaara.egg-info/SOURCES.txt'
running build_ext
test_found_section_not_command (test_cli.FindClosestMatchTests) ... ok
test_good_section_bad_section_good_section (test_cli.FindClosestMatchTests) ... ok
test_no_match_at_all (test_cli.FindClosestMatchTests) ... ok
test_successful_find_command (test_cli.FindClosestMatchTests) ... ok
test_valid_extensions (test_extensions.DirectoryExtensionsLoader) ... ok
test_load (test_extensions.ExtensionsManagerTests) ... ok
test_load_with_error (test_extensions.ExtensionsManagerTests) ... ok
test_invalid (test_parsers.ParseBooleanTests) ... ok
test_optional (test_parsers.ParseBooleanTests) ... ok
test_optional_empty_string (test_parsers.ParseBooleanTests) ... ok
test_optional_invalid (test_parsers.ParseBooleanTests) ... ok
test_optional_valid (test_parsers.ParseBooleanTests) ... ok
test_required (test_parsers.ParseBooleanTests) ... ok
test_valid_false (test_parsers.ParseBooleanTests) ... ok
test_valid_true (test_parsers.ParseBooleanTests) ... ok
test_basic_values (test_parsers.ParseCSVTests) ... ok
test_optional (test_parsers.ParseCSVTests) ... ok
test_optional_empty_string (test_parsers.ParseCSVTests) ... ok
test_optional_value (test_parsers.ParseCSVTests) ... ok
test_required (test_parsers.ParseCSVTests) ... ok
test_single_value (test_parsers.ParseCSVTests) ... ok
test_invalid (test_parsers.ParseIntTests) ... ok
test_valid (test_parsers.ParseIntTests) ... ok
test_negative (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_empty_string (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_invalid (test_parsers.ParseNonNegativeIntTests) ... ok
test_optional_valid (test_parsers.ParseNonNegativeIntTests) ... ok
test_string (test_parsers.ParseNonNegativeIntTests) ... ok
test_valid (test_parsers.ParseNonNegativeIntTests) ... ok
test_zero (test_parsers.ParseNonNegativeIntTests) ... ok
test_negative (test_parsers.ParsePostiveIntTests) ... ok
test_optional (test_parsers.ParsePostiveIntTests) ... ok
test_optional_empty_string (test_parsers.ParsePostiveIntTests) ... ok
test_optional_invalid (test_parsers.ParsePostiveIntTests) ... ok
test_optional_valid (test_parsers.ParsePostiveIntTests) ... ok
test_string (test_parsers.ParsePostiveIntTests) ... ok
test_valid (test_parsers.ParsePostiveIntTests) ... ok
test_zero (test_parsers.ParsePostiveIntTests) ... ok
test_color (test_prompt.GeneralTests)
Tests the color call correctly wraps the text with the correct markers. ... ok
test_read_interrupt (test_prompt.GeneralTests)
Tests that having read catch interrupt correctly returns the abort code. ... ok
test_write_color (test_prompt.GeneralTests)
Tests the color functionality built into write works. ... ok
test_write_with_wrap (test_prompt.GeneralTests)
Tests using an auto-wrap value correctly wraps text. ... ok
test_prompt_allow_empty (test_prompt.PromptTest)
Tests that a prompt will accept empty and not error. ... ok
test_prompt_menu (test_prompt.PromptTest)
Basic tests for prompting a menu of items and selecting a valid one. ... ok
test_prompt_no_empty (test_prompt.PromptTest)
Tests that a prompt that does not allow empty values re-prompts the user ... ok
test_prompt_non_interruptable (test_prompt.PromptTest)
Tests that a non-interruptable prompt properly raises an exception if interrupted. ... ok
test_prompt_password (test_prompt.PromptTest)
Make sure this correctly passes through to getpass one way or another ... ok
test_get_password (test_prompt.TestGetPassword) ... ok
test_py24_behavior (test_prompt.TestGetPassword) ... ok
test_py26_behavior (test_prompt.TestGetPassword) ... ok
test_wrap_long_wrap (test_prompt.WrapTests)
Tests that chop correctly handles data shorter than the chop length. ... ok
test_wrap_short_wrap (test_prompt.WrapTests)
Tests that chop correctly handled data longer than the chop length. ... ok
test_wrap_smart_split (test_prompt.WrapTests)
Tests smart wrapping to not break words. ... ok
test_wrap_with_none (test_prompt.WrapTests)
Tests that chop with a None wrap width doesn't crash. ... ok
test_equal_table_and_cols_no_separator (test_table.TableTests) ... ok
test_equal_table_and_cols_with_separator (test_table.TableTests) ... ok
test_larger_col_widths (test_table.TableTests) ... ok
test_larger_table_width (test_table.TableTests) ... ok
test_table_width_no_col_widths (test_table.TableTests) ... ok
test_invalid (test_validators.PartialValidateRegexTests) ... ok
test_valid (test_validators.PartialValidateRegexTests) ... ok
test_invalid (test_validators.ValidateBooleanTests) ... ok
test_valid (test_validators.ValidateBooleanTests) ... ok
test_invalid (test_validators.ValidateIntTests) ... ok
test_valid (test_validators.ValidateIntTests) ... ok

----------------------------------------------------------------------
Ran 66 tests in 0.047s

OK
```

I have also prepared specfile for RPM but it would be better to test it with new release before we push it.

Could you please check and merge this PR and make a new release?

### CODE REVIEW

**Comment by frenzymadness** [comment]
One more notice: this change adds dependency on 'future' module.

**Comment by frenzymadness** [comment]
Hello.

Is there any problem with my PR?

Have a nice day.

**Comment by jdob** [comment]
This is great, thanks!

**Comment by frenzymadness** [comment]
Thanks for merge. Will you do a new release soon?

**Comment by jdob** [comment]
I'll do one this afternoon or tomorrow morning.

**Comment by jdob** [comment]
I released 1.0.36 today with these changes. Thanks again :)

**Comment by frenzymadness** [comment]
@jdob Thank you very much. One last thing. Could you please make a new release on github too? Fedora package counts with .po files which are not present on PyPI release tarball.

**Pull request merged**
